name: Telegram Deploy

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version Name'
        required: true
        default: '1.0.0'
      version_code:
        description: 'Version Code'
        required: true
        default: '1'
      release_notes:
        description: 'Release Notes'
        required: true
        default: 'Bug fixes and improvements'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Update version info
      run: |
        # Update version in build.gradle.kts
        sed -i "s/versionCode = [0-9]*/versionCode = ${{ github.event.inputs.version_code }}/g" app/build.gradle.kts
        sed -i "s/versionName = \"[^\"]*\"/versionName = \"${{ github.event.inputs.version_name }}\"/g" app/build.gradle.kts
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build release APK
      run: ./gradlew assembleRelease
    
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"
    
    - name: Upload to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: multiclone-app-signed
        path: app/build/outputs/apk/release/*-signed.apk
    
    - name: Send to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🚀 New MultiClone App Release: ${{ github.event.inputs.version_name }} (${{ github.event.inputs.version_code }})
          
          📝 Release Notes:
          ${{ github.event.inputs.release_notes }}
        document: app/build/outputs/apk/release/*-signed.apk